export const UPDATE_PRODUCTS_CART = 'GET_PRODUCTS_CART';
export const DELETE_PRODUCTS_CART = 'DELETE_PRODUCTS_CART';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';
export const GET_USER = 'ERROR_REGISTER';
export const SUCESS_LOGIN = 'ERROR_REGISTER';
export const ERROR_LOGIN = 'ERROR_REGISTER';
export const CLOSE_SESSION = 'CLOSE_SESSION';